# Generated by Django 2.2.5 on 2019-09-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='page'),
        ),
    ]
