# Generated by Django 2.2.5 on 2019-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
    ]
