# Generated by Django 2.2.5 on 2019-12-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
